views/cart.py
from flask import Flask, Blueprint, render_template, current_app, request, redirect, url_for
from flask_login import current_user, login_required
from model import User, db
import requests

# Create the blueprint variable for routes and to register in the app factory
cart = Blueprint('cart', __name__)


@cart.route('/addToCart', methods=['POST'])
@login_required
def add_to_cart():
    # get the itemID from the POST request
    itemID = request.form['itemID']
    itemName = request.form['itemName']
    itemPrice = request.form['itemPrice']

    # get the userID of the current session

    userID = current_user.id

    # send a request to the cart and purchasing db to add the item to the cart of the current user
    requests.post('http://cart_purchasing:5004/add_to_cart',
                      data={'userID': userID, 'itemID': itemID, 'itemPrice': itemPrice, 'itemName': itemName})

    return redirect(url_for('items.item_listing'))


@cart.route('/cart')
@login_required
def cart_listing():

    # get the userID of the current session
    userID = current_user.id

    # get the cart for the current_user
    r = requests.post('http://cart_purchasing:5004/cart_list', data={'userID': userID})

    # calculate subtotal
    subtotal = 0
    for item in r.json():
        subtotal += float(item['itemPrice'])

    # return the page to be displayed for a cart
    return render_template('cart/cart.html', cart=r.json(), subtotal=subtotal)


@cart.route('/delete_from_cart', methods=['POST'])
@login_required
def cart_delete_item():

    # get the userID of the current session
    userID = current_user.id

    item_to_delete = request.form['delete']

    # get the cart for the current_user
    requests.post('http://cart_purchasing:5004/delete_item', data={'userID': userID, 'itemID': item_to_delete})

    # return the page to be displayed for a cart
    return redirect(url_for('cart.cart_listing'))

views/login.py
from flask import Blueprint, render_template, redirect, request, flash, url_for
from flask_login import login_user, logout_user, current_user
from model import User, db
import requests

# Create the blueprint variable for routes and to register in the app factory
login = Blueprint('login', __name__)


@login.route('/login/')
def login_page():
    """:return A login page"""
    return render_template("login/login.html")

@login.route('/login/', methods=['POST'])
def login_form():
    """Form handler for login page"""
    # get data from the login form
    email = request.form['email']
    password = request.form['password']

    # get a corresponding user object if the email exists in the user_db
    user = User.query.filter_by(email=email).first()

    # check if the user does not exist or if the password provided does not match the user_db
    if user is None or not user.check_password(password):
        flash('Invalid username or password, please try again.')
        return redirect(url_for('login.login_page'))

    # login the user
    login_user(user)

    # handle the redirect of the page
    next_page = request.args.get('next')
    if not next_page:
        next_page = url_for('items.item_listing')
    return redirect(next_page)


@login.route('/register/')
def register():
    """:return A registration page"""

    ## Create a test user when the register page is visited ##
    if User.query.filter_by(email='test@test.com').first() is None:
        test_user = User(first_name='Test', last_name='User', email='test@test.com')
        test_user.set_password('test')
        db.session.add(test_user)
        db.session.commit()

    return render_template("login/register.html")


@login.route('/register/', methods=['POST'])
def create_account():
    """Post method to create an account in the app
    """
    # get the data from the registration form
    first_name = request.form["first_name"]
    last_name = request.form["last_name"]
    email = request.form['email']
    password = request.form['password']

    # create a new user object with sqlalchemy, set the password and commit to the db
    user = User(first_name=first_name, last_name=last_name, email=email)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()

    return redirect(url_for("login.login_page"))

@login.route('/logout/')
def logout():
    """Logout a user from the current session"""
    userID = current_user.id
    requests.post('http://cart_purchasing:5004/delete_cart', data={'userID': userID})
    logout_user()

    return redirect(url_for('landing.index_page'))

views/profile.py
from flask import Blueprint, render_template
from flask_login import login_required

# Create the blueprint variable for routes and to register in the app factory
profile = Blueprint('profile', __name__)


@profile.route('/myProfile')
@login_required
def my_profile():
    """:return The profile page for the current user"""
    return render_template("profile/profile.html")

templates/cart/cart.html
{% extends "app_base.html" %}

{% block content %}
    <!-- Logo and Search -->
    <div class="row">
        <div class="col-md-3">
            <a href={{ url_for('items.item_listing') }}><img src="/static/logo2.jpg" width="30%"></a>
        </div>
    </div>
    <div class="row">
        <!-- Side bar -->
        <div class="col-md-3">
            <div class="panel">
                <h3 class="text-dark text-center">Menu</h3>
                <div class="panel-body">
                    <ul class="list-unstyled">
                        <li><a href={{ url_for('items.item_listing') }} class="list-group-item bg-active"><i
                                class="fa fa-angle-double-right"></i> Deals
                            <span class="badge">{{ count }}</span></a>
                        </li>
                        <li><a href={{ url_for('profile.my_profile') }} class="list-group-item"><i
                                class="fa fa-user"></i> My Profile</a></li>
                        <li><a href={{ url_for('cart.cart_listing') }} class="list-group-item"><i class="fa fa-user"></i> My Cart</a></li>
                        <li><a href={{ url_for('login.logout') }} class="list-group-item"><i
                                class="fa fa-power-off"></i> Log Out</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="panel text-dark">
                <div class="panel-body">
                    <table id="cart" class="table table-hover table-condensed">
                        <thead>
                        <tr>
                            <th style="width:50%">Product</th>
                            <th style="width:10%">Price</th>
                            <th style="width:22%" class="text-center">Subtotal</th>
                            <th style="width:10%"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in cart %}
                            <tr>
                                <td data-th="Product">
                                    <div class="row">
                                        <div class="col-sm-2 hidden-xs"><img src="/static/100x100.png" alt="..."
                                                                             class="img-responsive"/></div>
                                        <div class="col-sm-10">
                                            <h4 class="nomargin">{{ item['itemName'] }}</h4>
                                        </div>
                                    </div>
                                </td>
                                <td data-th="Price">${{ item['itemPrice'] }}</td>
                                <td class="actions" data-th="">
                                    <form action={{ url_for('cart.cart_delete_item') }} method="post">
                                        <button class="btn btn-danger btn-sm" type="submit" value={{ item['itemID'] }} name='delete'>
                                            <i class="glyphicon glyphicon-trash"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <tr>
                            <td><a href={{ url_for('items.item_listing') }} class="btn btn-warning">
                                <i class="glyphicon glyphicon-chevron-left"></i>
                                Continue Shopping</a>
                            </td>
                            <td colspan="2" class="hidden-xs"></td>
                            <td class="hidden-xs text-center"><strong>Total ${{ subtotal }}</strong></td>
                            <td><a href="#" class="btn btn-success btn-block">Checkout <i
                                    class="glyphicon glyphicon-chevron-right"></i></a>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    {{ super() }}
{% endblock %}