views/login.py
from flask import Blueprint, render_template, redirect, request, flash, url_for
from flask_login import login_user, logout_user, current_user
from model import User, db
import requests

# Create the blueprint variable for routes and to register in the app factory
login = Blueprint('login', __name__)


@login.route('/login/')
def login_page():
    """:return A login page"""
    return render_template("login/login.html")

@login.route('/login/', methods=['POST'])
def login_form():
    """Form handler for login page"""
    # get data from the login form
    email = request.form['email']
    password = request.form['password']

    # get a corresponding user object if the email exists in the user_db
    user = User.query.filter_by(email=email).first()

    # check if the user does not exist or if the password provided does not match the user_db
    if user is None or not user.check_password(password):
        flash('Invalid username or password, please try again.')
        return redirect(url_for('login.login_page'))

    # login the user
    login_user(user)

    # handle the redirect of the page
    next_page = request.args.get('next')
    if not next_page:
        next_page = url_for('items.item_listing')
    return redirect(next_page)


@login.route('/register/')
def register():
    """:return A registration page"""

    ## Create a test user when the register page is visited ##
    if User.query.filter_by(email='test@test.com').first() is None:
        test_user = User(first_name='Test', last_name='User', email='test@test.com')
        test_user.set_password('test')
        db.session.add(test_user)
        db.session.commit()

    return render_template("login/register.html")


@login.route('/register/', methods=['POST'])
def create_account():
    """Post method to create an account in the app
    """
    # get the data from the registration form
    first_name = request.form["first_name"]
    last_name = request.form["last_name"]
    email = request.form['email']
    password = request.form['password']

    # create a new user object with sqlalchemy, set the password and commit to the db
    user = User(first_name=first_name, last_name=last_name, email=email)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()

    return redirect(url_for("login.login_page"))

@login.route('/logout/')
def logout():
    """Logout a user from the current session"""
    userID = current_user.id
    requests.post('http://cart_purchasing:5004/delete_cart', data={'userID': userID})
    logout_user()

    return redirect(url_for('landing.index_page'))

templates/login/login.html
{# this blueprint contains the HTML for the login block including the username/password fields #}

{% extends "login/login_base.html" %}

{% block content %}
    {{ super() }}
    <div class="container">
        <div class="row" style="margin-top:20px">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                <img src="/static/logo2.jpg" width="100%">
                <form role="form" action={{ url_for('login.login_form') }} method="post">
                    <fieldset>
                        <h2 align="center">VIP Sign In</h2>
                        <hr>
                        <div class="container" style="min-height:100%; width:80%">
                            {% with messages = get_flashed_messages() %}
                                {% if messages %}
                                    {% for message in messages %}
                                        <div class="alert alert-danger alert-dismissible" role="alert">
                                            <button type="button" class="close" data-dismiss="alert"
                                                    aria-label="Close"><span aria-hidden="true">×</span></button>
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            {% endwith %}
                        </div>
                        <div class="form-group">
                            <input type="email" name="email" id="email" class="form-control input-lg"
                                   placeholder="Email Address">
                        </div>
                        <div class="form-group">
                            <input type="password" name="password" id="password" class="form-control input-lg"
                                   placeholder="Password">
                        </div>
                        <div class="row">
                            <!-- replace Forgot Password link -->
                            <a href="" class="btn btn-link pull-right">Forgot Password?</a>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <input type="submit" class="btn btn-lg btn-success btn-block" value="Sign In">
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <!-- replace link -->
                                <a href={{ url_for('login.register') }} class="btn btn-lg btn-primary btn-block">Register</a>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/login/login_base.html
{# this blueprint contains the HTML for the base login and register pages. This blueprint differs from the
app_base.html due to no nav bar#}

{# imports #}
{% import "bootstrap/wtf.html" as wtf %}

{# extends the bootstrap base template #}
{% extends "bootstrap/base.html" %}

{% block styles %}
    {{super()}}
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
{% endblock %}

{% block content %}
    {{ super() }}
{% endblock %}

templates/login/register.html
{# This blueprint contains the HTML for the register page to register a new user #}

{% extends "login/login_base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                <img src="/static/logo2.jpg" width="100%">
                <form role="form" action={{ url_for('login.create_account') }} method="POST">
                    <h2>Sign up to your VIP account</h2>
                    <hr>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="text" name="first_name" id="first_name" class="form-control input-lg" placeholder="First Name" tabindex="1">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="text" name="last_name" id="last_name" class="form-control input-lg" placeholder="Last Name" tabindex="2">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="email" name="email" id="email" class="form-control input-lg" placeholder="Email Address" tabindex="4">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password" tabindex="5">
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-xs-12 col-md-6"><input type="submit"  value="Register" class="btn btn-primary btn-block btn-lg" tabindex="7"></div>
                        <div class="col-xs-12 col-md-6"><a href={{ url_for('login.login_page') }} class="btn btn-success btn-block btn-lg">Sign In</a></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}