views/items.py
from flask import Blueprint, render_template, current_app, request
from flask_login import login_required
import requests
from flask_paginate import get_page_args
import util.pagination as paginate_functions

# Create the blueprint variable for routes and to register in the app factory
items = Blueprint('items', __name__)


@items.route('/items/')
@login_required
def item_listing():
    """:return The item page showing all search items"""

    # page is the variable assigned to getting the current page, eg '1'
    # per_page is configured in the util/pagination.cfg, represents the amount of items per page to be displayed
    # offset is a calculated value to use when querying the db for the next page's items to display
    page, per_page, offset = get_page_args(page_parameter='page', per_page_parameter='per_page')

    # search for all listings using a wildcard in the query (implemented in inventory_search)
    query_name = 'All'

    # send request to inventory_search to get all listings
    r = requests.post('http://inventory_search:5002/allListings',
                      data={'per_page': per_page, 'offset': offset})

    # Get count of items for pagination 'total' variable
    r_count = requests.get('http://inventory_search:5002/count_allListings')
    count = r_count.json()[0]['count']

    # set up a pagination object
    pagination = paginate_functions.get_pagination(current_app, page=page,
                                per_page=per_page,
                                total=count,
                                record_name='listings',
                                format_total = True,
                                format_number = True,)

    # return the page to be displayed with a pagination object
    return render_template("items/store_items.html",
                           items=r.json(),
                           query_name=query_name,
                           page=page,
                           count=count,
                           per_page=per_page,
                           pagination=pagination,
                           )


@items.route('/items/search/', defaults={'page': 1})
@items.route('/items/search/page/<int:page>/')
@login_required
def search(page):
    """:return a page giving the items relating to a search"""

    # page is the variable assigned to getting the current page, eg '1'
    # per_page is configured in the util/pagination.cfg, represents the amount of items per page to be displayed
    # offset is a calculated value to use when querying the db for the next page's items to display
    page, per_page, offset = get_page_args(page_parameter='page', per_page_parameter='per_page')


    # get args and set query arguments to search the inventory_db
    search_string = request.args.get('search')
    query_name = search_string

    # send request to inventory_search to search for search_query
    r = requests.post('http://inventory_search:5002/Search',
                      data={'per_page': per_page, 'offset': offset, 'search_string': search_string})

    # Get count of items for pagination 'total' variable
    r_count = requests.post('http://inventory_search:5002/count_Search',
                      data={'search_string': search_string})
    count = r_count.json()[0]['count']

    # set up a pagination object
    pagination = paginate_functions.get_pagination(current_app, page=page,
                                                   per_page=per_page,
                                                   total=count,
                                                   record_name='listings',
                                                   format_total=True,
                                                   format_number=True, )

    # return the page to be displayed with a pagination object
    return render_template("items/store_items.html",
                           items=r.json(),
                           query_name=query_name,
                           count=count,
                           page=page,
                           per_page=per_page,
                           pagination=pagination,
                           )

views/landing.py
from flask import Blueprint, render_template

# Create the blueprint variable for routes and to register in the app factory
landing = Blueprint('landing', __name__)


@landing.route('/')
def index_page():
    """:return The index/landing page"""
    return render_template("landing.html")

views/login.py
from flask import Blueprint, render_template, redirect, request, flash, url_for
from flask_login import login_user, logout_user, current_user
from model import User, db
import requests

# Create the blueprint variable for routes and to register in the app factory
login = Blueprint('login', __name__)


@login.route('/login/')
def login_page():
    """:return A login page"""
    return render_template("login/login.html")

@login.route('/login/', methods=['POST'])
def login_form():
    """Form handler for login page"""
    # get data from the login form
    email = request.form['email']
    password = request.form['password']

    # get a corresponding user object if the email exists in the user_db
    user = User.query.filter_by(email=email).first()

    # check if the user does not exist or if the password provided does not match the user_db
    if user is None or not user.check_password(password):
        flash('Invalid username or password, please try again.')
        return redirect(url_for('login.login_page'))

    # login the user
    login_user(user)

    # handle the redirect of the page
    next_page = request.args.get('next')
    if not next_page:
        next_page = url_for('items.item_listing')
    return redirect(next_page)


@login.route('/register/')
def register():
    """:return A registration page"""

    ## Create a test user when the register page is visited ##
    if User.query.filter_by(email='test@test.com').first() is None:
        test_user = User(first_name='Test', last_name='User', email='test@test.com')
        test_user.set_password('test')
        db.session.add(test_user)
        db.session.commit()

    return render_template("login/register.html")


@login.route('/register/', methods=['POST'])
def create_account():
    """Post method to create an account in the app
    """
    # get the data from the registration form
    first_name = request.form["first_name"]
    last_name = request.form["last_name"]
    email = request.form['email']
    password = request.form['password']

    # create a new user object with sqlalchemy, set the password and commit to the db
    user = User(first_name=first_name, last_name=last_name, email=email)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()

    return redirect(url_for("login.login_page"))

@login.route('/logout/')
def logout():
    """Logout a user from the current session"""
    userID = current_user.id
    requests.post('http://cart_purchasing:5004/delete_cart', data={'userID': userID})
    logout_user()

    return redirect(url_for('landing.index_page'))

views/profile.py
from flask import Blueprint, render_template
from flask_login import login_required

# Create the blueprint variable for routes and to register in the app factory
profile = Blueprint('profile', __name__)


@profile.route('/myProfile')
@login_required
def my_profile():
    """:return The profile page for the current user"""
    return render_template("profile/profile.html")

templates/app_base.html
{# This will be the base blueprint that all other blueprints will inherit.
The base contains a header and footer section that will be common to all pages excluding the login sections#}

{# extending the bootstrap base html layout
https://github.com/mbr/flask-bootstrap/blob/master/flask_bootstrap/templates/bootstrap/base.html#}
{% extends "bootstrap/base.html" %}

{# import browser compatibility fixes #}
{% import "bootstrap/fixes.html" as fixes %}

{% block head %}
    {{ super() }}
    <link rel="icon" href="/static/favicon.ico" type="image/x-icon">
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='style.css')}}">
{% endblock styles %}

{% block navbar %}
    {{ super() }}
    {{nav.top_nav.render()}}
{% endblock navbar %}

{% block content %}

    {% block footer %}
        <section class="footer bg-light py-5" id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h5>About The VIP Movie Club</h5>
                        <p>The VIP Movie Club is a solution for cinemas to advertise movie tickets and movie deals on an awesome
                        website that is fully managed and scalable for any company</p>
                    </div>
                    <div class="col-md-4" style="text-align: center">
                        <h5>Home</h5>
                        <ul class="list-unstyled">
                            <li><a href={{ url_for('items.item_listing') }}> Search</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4" style="text-align: center">
                        <h5>Account</h5>
                        <ul class="list-unstyled">
                            <li><a href={{ url_for('profile.my_profile') }}> My Profile</a></li>
                            <li><a href={{ url_for('cart.cart_listing') }} > My Cart</a></li>
                            <li><a href={{ url_for('login.login_page') }}> Login</a></li>
                            <li><a href={{ url_for('login.create_account') }}> Register</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    {% endblock footer %}
{% endblock content %}

templates/landing.html
{# this blueprint contains the HTML for the landing page #}

{% extends "app_base.html" %}

{% block content %}

    <div class="container">
        <div class="row" style="margin-top:20px">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                <h1 align="center"> Welcome to the VIP Movie Club!</h1>
            </div>
        </div>
        <div class="row" style="margin:20px 20px">
            <!-- Center the Search bar in the remaining row -->
            <div class="col-md-6 col-md-offset-3">
                <div id="custom-search-input">
                    <form class="input-group col-md-12" action={{ url_for('items.search') }} method="GET">
                        <input type="text" class="form-control input-lg" name="search"
                               placeholder="Search for a deal or movie ticket..."/>
                        <span class="input-group-btn">
                            <button class="btn btn-default btn-lg" type="submit">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </span>
                    </form>
                </div>
            </div>
        </div>
        <div class="row" style="margin: 20px 20px">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                <img src="/static/logo2.jpg" width="100%">
            </div>
        </div>
    </div>
    {{ super() }}
{% endblock %}