views/cart.py
from flask import Flask, Blueprint, render_template, current_app, request, redirect, url_for
from flask_login import current_user, login_required
from model import User, db
import requests

# Create the blueprint variable for routes and to register in the app factory
cart = Blueprint('cart', __name__)


@cart.route('/addToCart', methods=['POST'])
@login_required
def add_to_cart():
    # get the itemID from the POST request
    itemID = request.form['itemID']
    itemName = request.form['itemName']
    itemPrice = request.form['itemPrice']

    # get the userID of the current session

    userID = current_user.id

    # send a request to the cart and purchasing db to add the item to the cart of the current user
    requests.post('http://cart_purchasing:5004/add_to_cart',
                      data={'userID': userID, 'itemID': itemID, 'itemPrice': itemPrice, 'itemName': itemName})

    return redirect(url_for('items.item_listing'))


@cart.route('/cart')
@login_required
def cart_listing():

    # get the userID of the current session
    userID = current_user.id

    # get the cart for the current_user
    r = requests.post('http://cart_purchasing:5004/cart_list', data={'userID': userID})

    # calculate subtotal
    subtotal = 0
    for item in r.json():
        subtotal += float(item['itemPrice'])

    # return the page to be displayed for a cart
    return render_template('cart/cart.html', cart=r.json(), subtotal=subtotal)


@cart.route('/delete_from_cart', methods=['POST'])
@login_required
def cart_delete_item():

    # get the userID of the current session
    userID = current_user.id

    item_to_delete = request.form['delete']

    # get the cart for the current_user
    requests.post('http://cart_purchasing:5004/delete_item', data={'userID': userID, 'itemID': item_to_delete})

    # return the page to be displayed for a cart
    return redirect(url_for('cart.cart_listing'))

views/items.py
from flask import Blueprint, render_template, current_app, request
from flask_login import login_required
import requests
from flask_paginate import get_page_args
import util.pagination as paginate_functions

# Create the blueprint variable for routes and to register in the app factory
items = Blueprint('items', __name__)


@items.route('/items/')
@login_required
def item_listing():
    """:return The item page showing all search items"""

    # page is the variable assigned to getting the current page, eg '1'
    # per_page is configured in the util/pagination.cfg, represents the amount of items per page to be displayed
    # offset is a calculated value to use when querying the db for the next page's items to display
    page, per_page, offset = get_page_args(page_parameter='page', per_page_parameter='per_page')

    # search for all listings using a wildcard in the query (implemented in inventory_search)
    query_name = 'All'

    # send request to inventory_search to get all listings
    r = requests.post('http://inventory_search:5002/allListings',
                      data={'per_page': per_page, 'offset': offset})

    # Get count of items for pagination 'total' variable
    r_count = requests.get('http://inventory_search:5002/count_allListings')
    count = r_count.json()[0]['count']

    # set up a pagination object
    pagination = paginate_functions.get_pagination(current_app, page=page,
                                per_page=per_page,
                                total=count,
                                record_name='listings',
                                format_total = True,
                                format_number = True,)

    # return the page to be displayed with a pagination object
    return render_template("items/store_items.html",
                           items=r.json(),
                           query_name=query_name,
                           page=page,
                           count=count,
                           per_page=per_page,
                           pagination=pagination,
                           )


@items.route('/items/search/', defaults={'page': 1})
@items.route('/items/search/page/<int:page>/')
@login_required
def search(page):
    """:return a page giving the items relating to a search"""

    # page is the variable assigned to getting the current page, eg '1'
    # per_page is configured in the util/pagination.cfg, represents the amount of items per page to be displayed
    # offset is a calculated value to use when querying the db for the next page's items to display
    page, per_page, offset = get_page_args(page_parameter='page', per_page_parameter='per_page')


    # get args and set query arguments to search the inventory_db
    search_string = request.args.get('search')
    query_name = search_string

    # send request to inventory_search to search for search_query
    r = requests.post('http://inventory_search:5002/Search',
                      data={'per_page': per_page, 'offset': offset, 'search_string': search_string})

    # Get count of items for pagination 'total' variable
    r_count = requests.post('http://inventory_search:5002/count_Search',
                      data={'search_string': search_string})
    count = r_count.json()[0]['count']

    # set up a pagination object
    pagination = paginate_functions.get_pagination(current_app, page=page,
                                                   per_page=per_page,
                                                   total=count,
                                                   record_name='listings',
                                                   format_total=True,
                                                   format_number=True, )

    # return the page to be displayed with a pagination object
    return render_template("items/store_items.html",
                           items=r.json(),
                           query_name=query_name,
                           count=count,
                           page=page,
                           per_page=per_page,
                           pagination=pagination,
                           )

views/login.py
from flask import Blueprint, render_template, redirect, request, flash, url_for
from flask_login import login_user, logout_user, current_user
from model import User, db
import requests

# Create the blueprint variable for routes and to register in the app factory
login = Blueprint('login', __name__)


@login.route('/login/')
def login_page():
    """:return A login page"""
    return render_template("login/login.html")

@login.route('/login/', methods=['POST'])
def login_form():
    """Form handler for login page"""
    # get data from the login form
    email = request.form['email']
    password = request.form['password']

    # get a corresponding user object if the email exists in the user_db
    user = User.query.filter_by(email=email).first()

    # check if the user does not exist or if the password provided does not match the user_db
    if user is None or not user.check_password(password):
        flash('Invalid username or password, please try again.')
        return redirect(url_for('login.login_page'))

    # login the user
    login_user(user)

    # handle the redirect of the page
    next_page = request.args.get('next')
    if not next_page:
        next_page = url_for('items.item_listing')
    return redirect(next_page)


@login.route('/register/')
def register():
    """:return A registration page"""

    ## Create a test user when the register page is visited ##
    if User.query.filter_by(email='test@test.com').first() is None:
        test_user = User(first_name='Test', last_name='User', email='test@test.com')
        test_user.set_password('test')
        db.session.add(test_user)
        db.session.commit()

    return render_template("login/register.html")


@login.route('/register/', methods=['POST'])
def create_account():
    """Post method to create an account in the app
    """
    # get the data from the registration form
    first_name = request.form["first_name"]
    last_name = request.form["last_name"]
    email = request.form['email']
    password = request.form['password']

    # create a new user object with sqlalchemy, set the password and commit to the db
    user = User(first_name=first_name, last_name=last_name, email=email)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()

    return redirect(url_for("login.login_page"))

@login.route('/logout/')
def logout():
    """Logout a user from the current session"""
    userID = current_user.id
    requests.post('http://cart_purchasing:5004/delete_cart', data={'userID': userID})
    logout_user()

    return redirect(url_for('landing.index_page'))

views/profile.py
from flask import Blueprint, render_template
from flask_login import login_required

# Create the blueprint variable for routes and to register in the app factory
profile = Blueprint('profile', __name__)


@profile.route('/myProfile')
@login_required
def my_profile():
    """:return The profile page for the current user"""
    return render_template("profile/profile.html")

templates/items/store_items.html
{# this blueprint contains the HTML for the items page that will display all items of a related search #}


{% extends "app_base.html" %}

{% block content %}
    <!-- main body section -->
    <section class="py-5">
        <div class="container-fluid">
            <div class="row">
                <!-- Logo and Search -->
                <div class="col-md-3">
                    <a href={{ url_for('items.item_listing') }}><img src="/static/logo2.jpg" width="30%"></a>
                </div>
                <div class="col-md-9">
                    <!-- Center the Search bar in the remaining row -->
                    <div class="col-md-6 col-md-offset-3">
                        <div id="custom-search-input">
                            <form class="input-group col-md-12" action={{ url_for('items.search') }} method="GET">
                                <input type="text" class="form-control input-lg" name="search"
                                       placeholder="Search for a deal or movie ticket..."/>
                                <span class="input-group-btn">
                                    <button class="btn btn-default btn-lg" type="submit">
                                    <i class="glyphicon glyphicon-search"></i>
                                    </button>
                                </span>
                            </form>
                        </div>
                    </div>
                    <!-- Title of listings and query/pagination details -->
                    <div class="col-md-11 col-md-offset-1">
                        <h6>Search Items - '{{ query_name }}' {{ pagination.info }}</h6>
                    </div>
                </div>
            </div>

            <div class="row">
                <!-- Side bar -->
                <div class="col-md-2">
                    <div class="panel">
                        <h3 class="text-dark text-center">Menu</h3>
                        <div class="panel-body">
                            <ul class="list-unstyled">
                                <li><a href={{ url_for('items.item_listing') }} class="list-group-item bg-active"><i
                                        class="fa fa-angle-double-right"></i> Deals
                                    <span class="badge">{{ count }}</span></a>
                                </li>
                                <li><a href={{ url_for('profile.my_profile') }} class="list-group-item"><i
                                        class="fa fa-user"></i> My Profile</a></li>
                                <li><a href={{ url_for('cart.cart_listing') }} class="list-group-item"><i
                                        class="fa fa-user"></i> My Cart</a></li>
                                <li><a href={{ url_for('login.logout') }} class="list-group-item"><i
                                        class="fa fa-power-off"></i> Log Out</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <!-- Main listings -->
                <div class="col-md-10">
                    <div class="panel-dark pb-5">
                        <div class="panel-body-dark">
                            <div class="row mt-4">
                                <!-- Write out the card with title, price, description from db -->
                                {% for item in items %}
                                    <div class="col-md-4">
                                        <div class="panel panel-default text-center mb-2">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">{{ item['item_name'] }}</h4>
                                            </div>
                                            <div class="panel-body">
                                                <h6 class="mb-2 text-muted">${{ item['item_price'] }}</h6>
                                                <p style="color: black">{{ item['item_description'] }}</p>
                                            </div>
                                            <form id="addToCart" action={{ url_for('cart.add_to_cart') }} method="POST">
                                                <input type="hidden" name="itemName" value="{{ item['item_name'] }}">
                                                <input type="hidden" name="itemPrice" value="{{ item['item_price'] }}">
                                                <button class="btn btn-primary" type="submit" name="itemID"
                                                        value={{ item['itemID'] }}>Add To Cart
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="row">
                                {{ pagination.links }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer -->
    {{ super() }}
{% endblock %}